GCC = g++
TARGET = zork_game

all:
	g++ gameObjects.h gameObjects.cpp main.cpp Item.h Item.cpp Trigger.h Trigger.cpp Creature.h Creature.cpp Container.h Room.h Room.cpp Container.cpp utils.h utils.cpp