GCC = g++
TARGET = zork_game

all:
	g++ Commands.h Commands.cpp Conditions.h Conditions.cpp Container.h Container.cpp Creature.cpp Creature.h Item.h Item.cpp Owner.h Owner.cpp Room.cpp Attack.h Triggers.cpp Attack.cpp Room.h Status.h Status.cpp Triggers.h main.cpp utils.h utils.cpp